// Clang-module shim for the ScreenBridge core C ABI.
//
// The real header is generated by cbindgen at <repo>/include/screenbridge.h
// (PLAN.md §5, §6.4). This bare include is resolved at preprocessing time via
// the `-Xcc -I<repo>/include` flag the importing targets pass in Package.swift,
// so there is no absolute path baked into source.
#include "screenbridge.h"
