/*
 * ScreenBridge — C ABI for the Rust core.
 *
 * GENERATED FILE — do not edit by hand. Regenerate with `cargo build` (the
 * screenbridge-ffi build script runs cbindgen). Source of truth: the public
 * `#[no_mangle] extern "C"` items in core/crates/ffi/src/lib.rs (PLAN.md §6.4).
 */

#ifndef SCREENBRIDGE_H
#define SCREENBRIDGE_H

#pragma once

/* WARNING: this file is auto-generated by cbindgen; edits will be overwritten. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Round-trip "ping": returns `value + 1` (wrapping).
//
// This is the Phase 0 liveness check proving a native caller (Swift/C#) can
// invoke the Rust core across the C ABI and observe the returned value. The
// body cannot panic; the [`catch_unwind`] guard applies the §14 "no panic may
// cross the FFI" rule uniformly and yields `INT32_MIN` in the unreachable
// panic case.
int32_t sb_ping(int32_t value);

// Returns the locked wire-protocol major version (PLAN.md §6.1).
//
// Lets native UIs surface/negotiate the protocol version, and proves the FFI
// crate links the rest of the Rust workspace. Returns `0` only in the
// unreachable panic case.
uint16_t sb_protocol_version(void);

// Returns a pointer to a static, NUL-terminated UTF-8 version string.
//
// Ownership: the returned pointer is **borrowed**, has `'static` lifetime, and
// must NOT be freed by the caller. Returns `NULL` only in the unreachable panic
// case.
const char *sb_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SCREENBRIDGE_H */
